### PR TITLE
Dapp issues

### PR DESCRIPTION
**Pull request by VectoTec**
Resolves Issue #43 
- [x] Limit 50 DAI staking only
- [x] After verifying status, if we put the wrong address, it should not get verified [Frontend - issue]
- [x] It should always show verify alias if we mistakenly verify something else
- [x] After channel creation with Polygon alias, it should show msg switch to polygon network
- [x] Spam box icon change to #!$%

### CODE REVIEW

**Comment by VectoTec** [comment]
Removed slider from static data
image

**Comment by VectoTec** [comment]
Spam box icon changed
image

**Comment by VectoTec** [comment]
Verify alias on Polygon
image

**Comment by VectoTec** [comment]
Sending wrong address for verification issue:
image

Now, it itself fetches the correct Eth address, the user doesn't need to fill the address.
The input field is disabled now, user only has to click on verify alias button.

**Comment by Xand6r** [comment]
> Sending wrong address for verification issue: image
> 
> Now, it itself fetches the correct Eth address, the user doesn't need to fill the address. The input field is disabled now, user only has to click on verify alias button.

@VectoTec the whole point of this feature was to ensure that the person who was trying to verify the alias needs to know to eth address, to prevent spamming and such and as a protective measure, now if anyone creates an alias using my polygon address by mistake, i can just verify it even though it isnt mine and i can send notifications on their behalf

**Comment by akp111** [comment]
> thing

@Xand6r , We are already know which address is being used as alias address. So, by showing that putting that address in the input field, it would actually prevent the chances for someone to make mistake. Because if someone came with the intension to spam, he would do it anyway

**Pull request merged**
